version: 2.1

orbs:
  python: circleci/python@1.5.0

jobs:
  build-and-test:
    # docker:
    #   - image: cimg/python:3.10.2
    executor: python/default
    steps:
      - checkout
      # - python/load-cache
      # - python/install-deps
      # - python/save-cache
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: ./manage.py test

workflows:
  main:
    jobs:
      - build-and-test
